# Generated by Django 6.0.7 on 2026-07-29 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_modeloetiqueta_produto_curva_abc_and_more'),
        ('delivery', '0003_initial'),
        ('vendas', '0005_venda_troco_venda_valor_recebido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrega',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Entrega', 'verbose_name_plural': 'Entregas'},
        ),
        migrations.AddField(
            model_name='entrega',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.cliente'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entrega',
            name='contato_telefone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone de Contato'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='data_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Entrega'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='entrega',
            name='status_atribuido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='status_cancelada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='status_em_rota_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='status_entregue_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='status_pendente_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='entregador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('atribuido', 'Atribuído'), ('em_rota', 'Em Rota'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.venda'),
        ),
    ]
