# Generated by Django 6.0.7 on 2026-07-29 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo_lote', models.CharField(max_length=50)),
                ('data_fabricacao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField()),
                ('quantidade', models.IntegerField(default=0)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nota_fiscal', models.CharField(blank=True, max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='cadastros.produto')),
            ],
            options={
                'verbose_name': 'Lote',
                'ordering': ['-data_validade'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida'), ('ajuste', 'Ajuste'), ('perda', 'Perda'), ('devolucao', 'Devolucao'), ('transferencia', 'Transferencia')], max_length=13)),
                ('quantidade', models.IntegerField()),
                ('saldo_anterior', models.IntegerField(default=0)),
                ('saldo_posterior', models.IntegerField(default=0)),
                ('documento', models.CharField(blank=True, help_text='NF, receipt etc', max_length=50)),
                ('observacao', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='estoque.lote')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='cadastros.produto')),
            ],
            options={
                'verbose_name': 'Movimento Estoque',
                'ordering': ['-criado_em'],
            },
        ),
    ]
