# Generated by Django 6.0.7 on 2026-07-29 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('empresas', '0001_initial'),
        ('estoque', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100)),
                ('largura_mm', models.DecimalField(decimal_places=1, default=40, max_digits=5, verbose_name='Largura (mm)')),
                ('altura_mm', models.DecimalField(decimal_places=1, default=25, max_digits=5, verbose_name='Altura (mm)')),
                ('margem_superior', models.DecimalField(decimal_places=1, default=3, max_digits=5, verbose_name='Margem Superior (mm)')),
                ('margem_inferior', models.DecimalField(decimal_places=1, default=3, max_digits=5, verbose_name='Margem Inferior (mm)')),
                ('margem_esquerda', models.DecimalField(decimal_places=1, default=3, max_digits=5, verbose_name='Margem Esquerda (mm)')),
                ('margem_direita', models.DecimalField(decimal_places=1, default=3, max_digits=5, verbose_name='Margem Direita (mm)')),
                ('colunas', models.IntegerField(default=3, verbose_name='Colunas')),
                ('linhas', models.IntegerField(default=8, verbose_name='Linhas')),
                ('mostrar_nome', models.BooleanField(default=True, verbose_name='Mostrar Nome')),
                ('mostrar_preco', models.BooleanField(default=True, verbose_name='Mostrar Preço')),
                ('mostrar_codigo_barras', models.BooleanField(default=True, verbose_name='Mostrar Código de Barras')),
                ('mostrar_preco_custo', models.BooleanField(default=False, verbose_name='Mostrar Preço de Custo')),
                ('mostrar_laboratorio', models.BooleanField(default=False, verbose_name='Mostrar Laboratório')),
                ('mostrar_validade', models.BooleanField(default=False, verbose_name='Mostrar Validade')),
                ('fonte_tamanho', models.IntegerField(default=10, verbose_name='Tamanho da Fonte')),
                ('cabecalho', models.CharField(blank=True, max_length=200, verbose_name='Cabeçalho')),
                ('rodape', models.CharField(blank=True, max_length=200, verbose_name='Rodapé')),
            ],
            options={
                'verbose_name': 'Modelo de Etiqueta',
                'verbose_name_plural': 'Modelos de Etiquetas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='curva_abc',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='C', max_length=1, verbose_name='Curva ABC'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ultima_classificacao_abc',
            field=models.DateField(blank=True, null=True, verbose_name='Última Classificação ABC'),
        ),
        migrations.CreateModel(
            name='ClassificacaoABC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_calculo', models.DateField(auto_now_add=True, verbose_name='Data do Cálculo')),
                ('total_produtos', models.IntegerField(verbose_name='Total de Produtos')),
                ('total_vendas_periodo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total de Vendas no Período')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Classificação ABC',
                'verbose_name_plural': 'Classificações ABC',
                'ordering': ['-data_calculo'],
            },
        ),
        migrations.CreateModel(
            name='ImpressaoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_origem', models.CharField(choices=[('produto', 'Produto'), ('lote', 'Lote'), ('classe', 'Classe Terapêutica'), ('todos', 'Todos Produtos')], max_length=10, verbose_name='Tipo de Origem')),
                ('data_impressao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Impressão')),
                ('quantidade_copias', models.IntegerField(default=1, verbose_name='Quantidade de Cópias')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.modeloetiqueta', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Impressão de Etiqueta',
                'verbose_name_plural': 'Impressões de Etiquetas',
                'ordering': ['-data_impressao'],
            },
        ),
        migrations.CreateModel(
            name='ItemImpressaoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('impressao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cadastros.impressaoetiqueta', verbose_name='Impressão')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.lote', verbose_name='Lote')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item de Impressão',
                'verbose_name_plural': 'Itens de Impressão',
            },
        ),
    ]
