# Generated by Django 6.1 on 2026-08-22 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaPrivacidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('versao', models.CharField(default='1.0', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Politica de Privacidade',
                'verbose_name_plural': 'Politicas de Privacidade',
            },
        ),
        migrations.CreateModel(
            name='AcessoDadoSensiveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('rg', 'RG'), ('receita', 'Receita Medica'), ('outro', 'Outro')], max_length=20)),
                ('objeto_tipo', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(max_length=50)),
                ('motivo', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_dados_sensiveis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso a Dado Sensivel',
                'verbose_name_plural': 'Acessos a Dados Sensiveis',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Criar'), ('read', 'Consultar'), ('update', 'Atualizar'), ('delete', 'Excluir'), ('export', 'Exportar'), ('approve', 'Aprovar'), ('reject', 'Rejeitar'), ('cancel', 'Cancelar'), ('emit_nfe', 'Emitir NF-e'), ('emit_nfce', 'Emitir NFC-e'), ('open_cash', 'Abrir Caixa'), ('close_cash', 'Fechar Caixa'), ('sale', 'Venda')], max_length=20)),
                ('modelo', models.CharField(blank=True, default='', max_length=100)),
                ('objeto_id', models.CharField(blank=True, default='', max_length=50)),
                ('descricao', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('dados_novos', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_auditl_timesta_189a84_idx'), models.Index(fields=['usuario', '-timestamp'], name='core_auditl_usuario_84fe26_idx'), models.Index(fields=['empresa', '-timestamp'], name='core_auditl_empresa_66ce1a_idx'), models.Index(fields=['acao', '-timestamp'], name='core_auditl_acao_87212f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsentimentoLGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('termos', 'Termos de Uso'), ('privacidade', 'Politica de Privacidade'), ('marketing', 'Comunicacoes de Marketing'), ('cookies', 'Cookies')], max_length=20)),
                ('aceito', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consentimento LGPD',
                'verbose_name_plural': 'Consentimentos LGPD',
                'ordering': ['-timestamp'],
                'unique_together': {('usuario', 'tipo')},
            },
        ),
    ]
