# Generated by Django 6.1 on 2026-08-22 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaosistema',
            options={'verbose_name': 'Configuracao do Sistema', 'verbose_name_plural': 'Configuracoes do Sistema'},
        ),
        migrations.CreateModel(
            name='ConfigFiscalSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('certificado_a1', models.FileField(blank=True, upload_to='certificados/')),
                ('certificado_senha', models.CharField(blank=True, default='', max_length=200)),
                ('certificado_validade', models.DateField(blank=True, null=True)),
                ('cnae', models.CharField(blank=True, default='', max_length=10)),
                ('cnes', models.CharField(blank=True, default='', max_length=15)),
                ('codigo_municipio', models.CharField(blank=True, default='', max_length=7)),
                ('inscricao_municipal', models.CharField(blank=True, default='', max_length=20)),
                ('perfil_ecf', models.CharField(choices=[('A', 'A - ECF Sem Controle de Estoque'), ('B', 'B - ECF Sem Controle de Estoque com DAV'), ('C', 'C - ECF com Controle de Estoque')], default='A', max_length=1)),
                ('nfe_ambiente', models.CharField(choices=[('1', 'Producao'), ('2', 'Homologacao')], default='2', max_length=1)),
                ('nfe_versao', models.CharField(default='4.00', max_length=4)),
                ('nfe_serie', models.IntegerField(default=1)),
                ('nfe_numero_atual', models.IntegerField(default=0)),
                ('nfce_ambiente', models.CharField(choices=[('1', 'Producao'), ('2', 'Homologacao')], default='2', max_length=1)),
                ('nfce_versao', models.CharField(default='4.00', max_length=4)),
                ('nfce_serie', models.IntegerField(default=1)),
                ('nfce_numero_atual', models.IntegerField(default=0)),
                ('nfce_csc_id', models.CharField(blank=True, default='', max_length=6)),
                ('nfce_csc_token', models.CharField(blank=True, default='', max_length=36)),
                ('sped_fiscal', models.BooleanField(default=False)),
                ('sped_contabil', models.BooleanField(default=False)),
                ('sped_contribuicoes', models.BooleanField(default=False)),
                ('sintegra', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Configuracao Fiscal',
                'verbose_name_plural': 'Configuracoes Fiscais',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('backup_automatico', models.BooleanField(default=False)),
                ('backup_frequencia', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], default='diario', max_length=10)),
                ('backup_hora', models.TimeField(default='02:00')),
                ('backup_manter_dias', models.IntegerField(default=30)),
                ('backup_local', models.CharField(default='/backups', max_length=200)),
                ('ultimo_backup', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Configuracao de Backup',
                'verbose_name_plural': 'Configuracoes de Backup',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=200)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, default='', max_length=200)),
                ('smtp_senha', models.CharField(blank=True, default='', max_length=200)),
                ('smtp_usa_tls', models.BooleanField(default=True)),
                ('email_remetente', models.CharField(blank=True, default='', max_length=200)),
                ('nome_remetente', models.CharField(blank=True, default='pharmaMS', max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Configuracao de Email',
                'verbose_name_plural': 'Configuracoes de Email',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('aliquota_issqn', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('aliquota_pis', models.DecimalField(decimal_places=2, default=1.65, max_digits=5)),
                ('aliquota_cofins', models.DecimalField(decimal_places=2, default=7.6, max_digits=5)),
                ('aliquota_icms_padrao', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('aliquota_fcp', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cnae_principal', models.CharField(blank=True, default='', max_length=10)),
                ('natureza_operacao', models.CharField(default='Venda de Mercadoria', max_length=200)),
                ('regime_tributario', models.CharField(choices=[('1', 'Simples Nacional'), ('2', 'Simples Nacional - Excesso de Sublimite'), ('3', 'Regime Normal'), ('4', 'Microempreendedor Individual (MEI)')], default='1', max_length=1)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Configuracao Municipal',
                'verbose_name_plural': 'Configuracoes Municipais',
            },
        ),
    ]
