# Generated by Django 6.0.7 on 2026-07-29 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_modeloetiqueta_produto_curva_abc_and_more'),
        ('empresas', '0001_initial'),
        ('vendas', '0002_venda_vendedor_comissaovenda_regracomissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('produto', 'Por Produto'), ('classe', 'Por Classe'), ('geral', 'Geral'), ('quantidade', 'Leve X Pague Y'), ('combo', 'Combo')], max_length=10)),
                ('percentual_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quantidade_minima', models.IntegerField(blank=True, help_text='Para leve X pague Y', null=True)),
                ('quantidade_cobrar', models.IntegerField(blank=True, help_text='Pague Y itens', null=True)),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('dias_semana', models.CharField(blank=True, help_text='1,2,3,4,5,6,7 - dias da semana', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('limite_por_cliente', models.IntegerField(default=0, help_text='0 = ilimitado')),
                ('classe_terapeutica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.classeterapeutica')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto')),
            ],
            options={
                'verbose_name': 'Promocao',
                'verbose_name_plural': 'Promocoes',
            },
        ),
    ]
