# Generated by Django 6.0.7 on 2026-07-29 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_modeloetiqueta_produto_curva_abc_and_more'),
        ('empresas', '0001_initial'),
        ('estoque', '0002_initial'),
        ('vendas', '0003_promocao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='nfce_emitida',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='aberto', max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('total_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_descontos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_geral', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dav_origem', to='vendas.venda')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DAV',
                'verbose_name_plural': 'DAVs',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemDAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.dav')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.lote')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
