# Generated by Django 6.0.7 on 2026-07-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_venda_nfce_emitida_dav_itemdav'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='troco',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Troco a devolver', max_digits=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_recebido',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor pago pelo cliente', max_digits=10),
        ),
    ]
