# Generated by Django 6.0.7 on 2026-07-29 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('aplicacao', models.CharField(blank=True, help_text='1-Entrada 2-Saida', max_length=1)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='NCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sintegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('periodo', models.CharField(help_text='MM/AAAA', max_length=7)),
                ('arquivo_gerado', models.FileField(blank=True, upload_to='fiscal/sintegra/')),
                ('processado', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpedContribuicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('periodo', models.CharField(help_text='MM/AAAA', max_length=7)),
                ('tipo_contribuicao', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral')], default='mensal', max_length=10)),
                ('arquivo_gerado', models.FileField(blank=True, upload_to='fiscal/sped/')),
                ('processado', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('serie_nfe', models.IntegerField(default=1)),
                ('serie_nfce', models.IntegerField(default=1)),
                ('proximo_numero_nfe', models.IntegerField(default=1)),
                ('proximo_numero_nfce', models.IntegerField(default=1)),
                ('regime_tributario', models.CharField(choices=[('1', 'Simples Nacional'), ('2', 'Simples Excesso'), ('3', 'Regime Normal')], default='1', max_length=1)),
                ('certificado_digital', models.FileField(blank=True, upload_to='fiscal/certificados/')),
                ('senha_certificado', models.CharField(blank=True, max_length=100)),
                ('csc', models.CharField(blank=True, max_length=100)),
                ('csc_id', models.CharField(blank=True, max_length=10)),
                ('token_ibpt', models.CharField(blank=True, max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('modelo', models.CharField(choices=[('55', 'NF-e'), ('65', 'NFC-e')], default='55', max_length=2)),
                ('serie', models.IntegerField(default=1)),
                ('numero', models.IntegerField()),
                ('chave_acesso', models.CharField(blank=True, max_length=50)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('autorizada', 'Autorizada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada'), ('denegada', 'Denegada')], default='pendente', max_length=20)),
                ('protocolo', models.CharField(blank=True, max_length=50)),
                ('xml_gerado', models.FileField(blank=True, upload_to='fiscal/xml_gerado/')),
                ('xml_retorno', models.FileField(blank=True, upload_to='fiscal/xml_retorno/')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'NF-e/NFC-e',
                'ordering': ['-criado_em'],
            },
        ),
    ]
