# Generated by Django 6.0.7 on 2026-07-29 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('fiscal', '0002_initial'),
        ('vendas', '0003_promocao'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('numero', models.CharField(max_length=20)),
                ('serie', models.IntegerField(default=1)),
                ('chave_acesso', models.CharField(max_length=44, unique=True)),
                ('modelo', models.CharField(choices=[('65', 'NFC-e (65)')], default='65', max_length=2)),
                ('tipo_emissao', models.CharField(choices=[('1', 'Normal'), ('2', 'Contingencia')], default='1', max_length=1)),
                ('status_autorizacao', models.CharField(choices=[('pendente', 'Pendente'), ('autorizada', 'Autorizada'), ('denegada', 'Denegada'), ('cancelada', 'Cancelada')], default='pendente', max_length=10)),
                ('xml_enviado', models.TextField(blank=True)),
                ('xml_retorno', models.TextField(blank=True)),
                ('protocolo', models.CharField(blank=True, max_length=20)),
                ('numero_lote', models.CharField(blank=True, max_length=20)),
                ('data_autorizacao', models.DateTimeField(blank=True, null=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('justificativa_contingencia', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfces', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'NFC-e',
                'verbose_name_plural': 'NFC-e',
                'ordering': ['-criado_em'],
            },
        ),
    ]
