# Generated by Django 6.0.7 on 2026-07-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_nfce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfe',
            name='xml_gerado',
        ),
        migrations.AddField(
            model_name='nfe',
            name='data_autorizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfe',
            name='xml_enviado',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='xml_retorno',
            field=models.TextField(blank=True),
        ),
    ]
