# Generated by Django 6.0.7 on 2026-07-29 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('admin_master', 'Admin Master'), ('admin_empresa', 'Admin Empresa'), ('gerente', 'Gerente'), ('supervisor', 'Supervisor'), ('farmaceutico', 'Farmaceutico'), ('atendente', 'Atendente'), ('entregador', 'Entregador')], default='atendente', max_length=30),
        ),
        migrations.CreateModel(
            name='HistoricoCancelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('venda', 'Venda'), ('dav', 'DAV'), ('nfce', 'NFC-e'), ('lancamento', 'Lancamento Financeiro')], max_length=10)),
                ('objeto_id', models.IntegerField()),
                ('objeto_str', models.CharField(max_length=200)),
                ('motivo', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historico de Cancelamento',
                'verbose_name_plural': 'Historicos de Cancelamento',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='RegraLiberacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('cancelar_venda', 'Cancelar Venda'), ('cancelar_dav', 'Cancelar DAV'), ('cancelar_nfce', 'Cancelar NFC-e'), ('desconto_especial', 'Desconto Especial'), ('reabrir_caixa', 'Reabrir Caixa'), ('ajuste_estoque', 'Ajuste de Estoque'), ('outro', 'Outro')], max_length=20)),
                ('perfil_aprovador', models.CharField(choices=[('gerente', 'Gerente'), ('supervisor', 'Supervisor'), ('admin', 'Administrador')], max_length=20)),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Regra de Liberacao',
                'verbose_name_plural': 'Regras de Liberacao',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoLiberacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('cancelar_venda', 'Cancelar Venda'), ('cancelar_dav', 'Cancelar DAV'), ('cancelar_nfce', 'Cancelar NFC-e'), ('desconto_especial', 'Desconto Especial'), ('reabrir_caixa', 'Reabrir Caixa'), ('ajuste_estoque', 'Ajuste de Estoque'), ('outro', 'Outro')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10)),
                ('motivo', models.TextField()),
                ('observacao_aprovador', models.TextField(blank=True, default='')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_aprovadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitacao de Liberacao',
                'verbose_name_plural': 'Solicitacoes de Liberacao',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
