# Generated by Django 6.0.7 on 2026-07-29 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('fiscal', '0003_nfce'),
        ('usuarios', '0002_alter_usuario_perfil_historicocancelamento_and_more'),
        ('vendas', '0004_venda_nfce_emitida_dav_itemdav'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoliberacao',
            name='dav',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.dav'),
        ),
        migrations.AddField(
            model_name='solicitacaoliberacao',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='solicitacaoliberacao',
            name='nfce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscal.nfe'),
        ),
        migrations.AddField(
            model_name='solicitacaoliberacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_feitas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaoliberacao',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.venda'),
        ),
        migrations.AddField(
            model_name='historicocancelamento',
            name='liberacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.solicitacaoliberacao'),
        ),
    ]
