# Generated by Django 6.0.7 on 2026-07-29 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseTerapeuticaSNGPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfissionalSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=200)),
                ('conselho', models.CharField(choices=[('CRM', 'CRM'), ('COREN', 'COREN'), ('CRO', 'CRO'), ('CRF', 'CRF')], max_length=10)),
                ('numero_conselho', models.CharField(max_length=30)),
                ('uf_conselho', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicamentoControlado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_receita', models.CharField(choices=[('amarela', 'Amarela (B1)'), ('azul', 'Azul (B2)'), ('branco_comum', 'Branco Comum'), ('branco_especial', 'Branco Especial'), ('antibiotico', 'Antibiotico'), ('retinoico', 'Retinoico'), ('anabolizante', 'Anabolizante')], max_length=20)),
                ('concentracao', models.CharField(blank=True, max_length=100)),
                ('classe_terapeutica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sngpc.classeterapeuticasngpc')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receituario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('numero_receita', models.CharField(max_length=30)),
                ('paciente_nome', models.CharField(max_length=200)),
                ('paciente_cpf', models.CharField(blank=True, max_length=18)),
                ('data_emissao', models.DateField()),
                ('data_validade', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sngpc.profissionalsaude')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoSNGPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida'), ('perda', 'Perda'), ('devolucao', 'Devolucao'), ('inventario', 'Inventario')], max_length=10)),
                ('quantidade', models.IntegerField()),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sngpc.medicamentocontrolado')),
                ('receituario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sngpc.receituario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemReceituario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade', models.IntegerField()),
                ('posologia', models.CharField(blank=True, max_length=200)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sngpc.medicamentocontrolado')),
                ('receituario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='sngpc.receituario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelatorioSNGPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('bspo', 'BSPO'), ('bmpo', 'BMPO'), ('rmnra', 'RMNRA'), ('rmnrb', 'RMNRB'), ('inventario', 'Inventario')], max_length=20)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('arquivo_xml', models.FileField(blank=True, upload_to='sngpc/relatorios/')),
                ('processado', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
