# Generated by Django 6.1 on 2026-08-22 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_modeloetiqueta_produto_curva_abc_and_more'),
        ('sngpc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentocontrolado',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto'),
        ),
    ]
