# Generated by Django 6.0.7 on 2026-07-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='diferenca',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Diferenca entre esperado e contado', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caixa',
            name='observacoes_fechamento',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='caixa',
            name='saldo_em_cartao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caixa',
            name='saldo_em_convenio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caixa',
            name='saldo_em_especie',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor em dinheiro contado', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caixa',
            name='saldo_em_pix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
