# Generated by Django 6.1 on 2026-08-22 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('pedido_confirmado', 'Pedido Confirmado'), ('pedido_enviado', 'Pedido Enviado'), ('pedido_entregue', 'Pedido Entregue'), ('promocao', 'Promocao'), ('lembrete', 'Lembretes'), ('nfe', 'Envio de NF-e'), ('personalizado', 'Personalizado')], max_length=50)),
                ('corpo', models.TextField(help_text='Use {variavel} para campos dinamicos')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Template WhatsApp',
                'verbose_name_plural': 'Templates WhatsApp',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MensagemWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('destinatario_nome', models.CharField(max_length=200)),
                ('destinatario_telefone', models.CharField(max_length=20)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('entregue', 'Entregue'), ('lida', 'Lida'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('erro_detalhes', models.TextField(blank=True, default='')),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.templatewhatsapp')),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'ordering': ['-criado_em'],
            },
        ),
    ]
