# Generated by Django 6.1 on 2026-08-22 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemwhatsapp',
            name='direcao',
            field=models.CharField(choices=[('enviada', 'Enviada'), ('recebida', 'Recebida')], default='enviada', max_length=10),
        ),
        migrations.AddField(
            model_name='mensagemwhatsapp',
            name='mensagem_id',
            field=models.CharField(blank=True, default='', help_text='ID da mensagem no Evolution API', max_length=100),
        ),
        migrations.AlterField(
            model_name='mensagemwhatsapp',
            name='destinatario_nome',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mensagemwhatsapp',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('entregue', 'Entregue'), ('lida', 'Lida'), ('erro', 'Erro'), ('recebida', 'Recebida')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='ConversaWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('telefone', models.CharField(max_length=20)),
                ('nome', models.CharField(blank=True, default='', max_length=200)),
                ('etapa', models.CharField(choices=[('inicio', 'Inicio'), ('menu_principal', 'Menu Principal'), ('aguardando_pedido', 'Aguardando Numero do Pedido'), ('aguardando_atendente', 'Aguardando Atendente'), ('conversa_ativa', 'Conversa Ativa')], default='inicio', max_length=50)),
                ('ultimo_mensagem_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Conversa WhatsApp',
                'verbose_name_plural': 'Conversas WhatsApp',
                'ordering': ['-ultimo_mensagem_em'],
            },
        ),
        migrations.AddField(
            model_name='mensagemwhatsapp',
            name='conversa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whatsapp.conversawhatsapp'),
        ),
        migrations.CreateModel(
            name='EvolutionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instancia', models.CharField(help_text='Nome da instancia no Evolution API', max_length=100)),
                ('api_url', models.URLField(help_text='URL base do Evolution API (ex: http://localhost:8080)')),
                ('api_key', models.CharField(help_text='API Key do Evolution API', max_length=255)),
                ('webhook_url', models.URLField(blank=True, default='', help_text='URL do webhook (preenchido automaticamente)')),
                ('ativo', models.BooleanField(default=True)),
                ('auto_responder', models.BooleanField(default=True, help_text='Ativar agente automatico para responder mensagens')),
                ('mensagem_boas_vindas', models.TextField(default='Ola! Bem-vindo a {empresa}! Como posso ajudar?\n\n1 - Ver promocoes\n2 - Consultar pedido\n3 - Falar com atendente\n4 - Horario de funcionamento', help_text='Mensagem enviada quando o cliente envia a primeira mensagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Configuracao Evolution API',
                'verbose_name_plural': 'Configuracoes Evolution API',
                'ordering': ['-criado_em'],
            },
        ),
    ]
