# Generated by Django 6.0.7 on 2026-07-29 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperadoraPBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('farmacia_popular', 'Farmacia Popular'), ('vidalink', 'Vidalink'), ('orizon', 'Orizon'), ('trncentre', 'TRNCentre'), ('pharmalink', 'Pharmalink'), ('funcional_card', 'Funcional Card'), ('epharma', 'e-Pharma')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemTransacaoPBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_aprovado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransacaoPBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('autorizada', 'Autorizada'), ('negada', 'Negada'), ('processada', 'Processada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('numero_autorizacao', models.CharField(blank=True, max_length=50)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_repassado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_autorizacao', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('operadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pbm.operadorapbm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
