# Generated by Django 6.0.7 on 2026-07-29 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pbm', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaopbm',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.venda'),
        ),
        migrations.AddField(
            model_name='itemtransacaopbm',
            name='transacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pbm.transacaopbm'),
        ),
    ]
