# Generated by Django 6.0.7 on 2026-07-29 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_modeloetiqueta_produto_curva_abc_and_more'),
        ('compras', '0002_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugestaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_geracao', models.DateField(auto_now_add=True)),
                ('data_inicio_analise', models.DateField()),
                ('data_fim_analise', models.DateField()),
                ('processada', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='empresas.empresa')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugestoes', to='compras.pedidocompra')),
            ],
            options={
                'verbose_name': 'Sugestão de Compra',
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.CreateModel(
            name='ItemSugestaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('estoque_atual', models.IntegerField()),
                ('estoque_minimo', models.IntegerField()),
                ('vendas_periodo', models.IntegerField()),
                ('dias_estoque', models.IntegerField()),
                ('sugestao_compra', models.IntegerField()),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], max_length=5)),
                ('aprovado', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto')),
                ('sugestao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.sugestaocompra')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
