# Generated by Django 6.0.7 on 2026-07-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('ie', models.CharField(blank=True, default='', max_length=20)),
                ('endereco', models.CharField(blank=True, default='', max_length=255)),
                ('bairro', models.CharField(blank=True, default='', max_length=100)),
                ('cidade', models.CharField(blank=True, default='', max_length=100)),
                ('uf', models.CharField(blank=True, default='', max_length=2)),
                ('cep', models.CharField(blank=True, default='', max_length=9)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
